import { HardwareSKU, DeploymentType } from '@/types';

// Hardware SKUs based on Elastic Cloud pricing table structure
// These represent real-world instance types available across different cloud providers
export const HARDWARE_SKUS: HardwareSKU[] = [
  // Elastic Cloud SKUs (similar to cloud.elastic.co pricing)
  {
    id: 'elastic-cloud-1gb',
    name: '1 GB RAM',
    description: 'Development and testing',
    storageType: 'ssd',
    storageSizeGB: 64,
    cpuCores: 1,
    memoryGB: 1,
    iops: 3000,
    throughputMBps: 125,
    costPerMonth: 16,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-2gb',
    name: '2 GB RAM',
    description: 'Small workloads',
    storageType: 'ssd',
    storageSizeGB: 64,
    cpuCores: 1,
    memoryGB: 2,
    iops: 3000,
    throughputMBps: 125,
    costPerMonth: 32,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-4gb',
    name: '4 GB RAM',
    description: 'Standard workloads',
    storageType: 'ssd',
    storageSizeGB: 120,
    cpuCores: 2,
    memoryGB: 4,
    iops: 3000,
    throughputMBps: 250,
    costPerMonth: 64,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-8gb',
    name: '8 GB RAM',
    description: 'Production workloads',
    storageType: 'ssd',
    storageSizeGB: 240,
    cpuCores: 2,
    memoryGB: 8,
    iops: 5000,
    throughputMBps: 500,
    costPerMonth: 128,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-16gb',
    name: '16 GB RAM',
    description: 'High performance',
    storageType: 'ssd',
    storageSizeGB: 512,
    cpuCores: 4,
    memoryGB: 16,
    iops: 10000,
    throughputMBps: 1000,
    costPerMonth: 256,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-32gb',
    name: '32 GB RAM',
    description: 'Enterprise workloads',
    storageType: 'ssd',
    storageSizeGB: 1024,
    cpuCores: 8,
    memoryGB: 32,
    iops: 20000,
    throughputMBps: 2000,
    costPerMonth: 512,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-64gb',
    name: '64 GB RAM',
    description: 'Large scale',
    storageType: 'ssd',
    storageSizeGB: 2048,
    cpuCores: 16,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 1024,
    deploymentTypes: ['elastic_cloud'],
  },
  {
    id: 'elastic-cloud-128gb',
    name: '128 GB RAM',
    description: 'Very large scale',
    storageType: 'nvme',
    storageSizeGB: 4096,
    cpuCores: 32,
    memoryGB: 128,
    iops: 50000,
    throughputMBps: 4000,
    costPerMonth: 2048,
    deploymentTypes: ['elastic_cloud'],
  },

  // AWS EC2 Instance Types
  {
    id: 'aws-t3-small',
    name: 't3.small',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 20,
    cpuCores: 2,
    memoryGB: 2,
    iops: 3000,
    throughputMBps: 125,
    costPerMonth: 15,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-t3-medium',
    name: 't3.medium',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 20,
    cpuCores: 2,
    memoryGB: 4,
    iops: 3000,
    throughputMBps: 250,
    costPerMonth: 30,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-m5-large',
    name: 'm5.large',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 2,
    memoryGB: 8,
    iops: 3000,
    throughputMBps: 500,
    costPerMonth: 70,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-m5-xlarge',
    name: 'm5.xlarge',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 200,
    cpuCores: 4,
    memoryGB: 16,
    iops: 6000,
    throughputMBps: 1000,
    costPerMonth: 140,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-m5-2xlarge',
    name: 'm5.2xlarge',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 400,
    cpuCores: 8,
    memoryGB: 32,
    iops: 10000,
    throughputMBps: 2000,
    costPerMonth: 280,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-m5-4xlarge',
    name: 'm5.4xlarge',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 800,
    cpuCores: 16,
    memoryGB: 64,
    iops: 20000,
    throughputMBps: 3000,
    costPerMonth: 560,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-i3-xlarge',
    name: 'i3.xlarge',
    description: 'Storage optimized',
    storageType: 'nvme',
    storageSizeGB: 950,
    cpuCores: 4,
    memoryGB: 30,
    iops: 50000,
    throughputMBps: 2000,
    costPerMonth: 312,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-i3-2xlarge',
    name: 'i3.2xlarge',
    description: 'Storage optimized',
    storageType: 'nvme',
    storageSizeGB: 1900,
    cpuCores: 8,
    memoryGB: 61,
    iops: 100000,
    throughputMBps: 3000,
    costPerMonth: 624,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-d2-xlarge',
    name: 'd2.xlarge',
    description: 'Dense storage',
    storageType: 'hdd',
    storageSizeGB: 6000,
    cpuCores: 4,
    memoryGB: 30,
    iops: 300,
    throughputMBps: 200,
    costPerMonth: 690,
    deploymentTypes: ['aws'],
  },

  // AWS Tested PB-Scale Configurations (based on real-world testing)
  {
    id: 'aws-pb-hot',
    name: 'PB-Scale Hot Tier',
    description: 'Tested: 160 nodes, 0-hour retention',
    storageType: 'ssd',
    storageSizeGB: 4096, // 4 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 900,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-pb-cold',
    name: 'PB-Scale Cold Tier',
    description: 'Tested: 60 nodes, 24-hour lookback',
    storageType: 'ssd',
    storageSizeGB: 10240, // 10 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 1300,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-pb-frozen',
    name: 'PB-Scale Frozen Tier',
    description: 'Tested: 66 nodes, searchable snapshots',
    storageType: 'hdd',
    storageSizeGB: 10240, // 10 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 500,
    throughputMBps: 300,
    costPerMonth: 1100,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-pb-master',
    name: 'PB-Scale Master Node',
    description: 'Tested: 3 nodes, no data storage',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 700,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-pb-ml',
    name: 'PB-Scale ML Node',
    description: 'Tested: 1 node, machine learning',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 700,
    deploymentTypes: ['aws'],
  },
  {
    id: 'aws-pb-kibana',
    name: 'PB-Scale Kibana/UI Node',
    description: 'Tested: 2 nodes, UI interface',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 700,
    deploymentTypes: ['aws'],
  },

  // GCP Instance Types
  {
    id: 'gcp-n1-standard-1',
    name: 'n1-standard-1',
    description: 'Standard machine',
    storageType: 'ssd',
    storageSizeGB: 10,
    cpuCores: 1,
    memoryGB: 3.75,
    iops: 3000,
    throughputMBps: 125,
    costPerMonth: 25,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-standard-2',
    name: 'n1-standard-2',
    description: 'Standard machine',
    storageType: 'ssd',
    storageSizeGB: 20,
    cpuCores: 2,
    memoryGB: 7.5,
    iops: 3000,
    throughputMBps: 250,
    costPerMonth: 50,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-standard-4',
    name: 'n1-standard-4',
    description: 'Standard machine',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 4,
    memoryGB: 15,
    iops: 6000,
    throughputMBps: 500,
    costPerMonth: 100,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-standard-8',
    name: 'n1-standard-8',
    description: 'Standard machine',
    storageType: 'ssd',
    storageSizeGB: 200,
    cpuCores: 8,
    memoryGB: 30,
    iops: 10000,
    throughputMBps: 1000,
    costPerMonth: 200,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-standard-16',
    name: 'n1-standard-16',
    description: 'Standard machine',
    storageType: 'ssd',
    storageSizeGB: 400,
    cpuCores: 16,
    memoryGB: 60,
    iops: 20000,
    throughputMBps: 2000,
    costPerMonth: 400,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-highmem-2',
    name: 'n1-highmem-2',
    description: 'High memory',
    storageType: 'ssd',
    storageSizeGB: 20,
    cpuCores: 2,
    memoryGB: 13,
    iops: 3000,
    throughputMBps: 250,
    costPerMonth: 60,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-highmem-4',
    name: 'n1-highmem-4',
    description: 'High memory',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 4,
    memoryGB: 26,
    iops: 6000,
    throughputMBps: 500,
    costPerMonth: 120,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-n1-highmem-8',
    name: 'n1-highmem-8',
    description: 'High memory',
    storageType: 'ssd',
    storageSizeGB: 200,
    cpuCores: 8,
    memoryGB: 52,
    iops: 10000,
    throughputMBps: 1000,
    costPerMonth: 240,
    deploymentTypes: ['gcp'],
  },

  // GCP Tested PB-Scale Configurations (based on real-world testing)
  {
    id: 'gcp-pb-hot',
    name: 'PB-Scale Hot Tier',
    description: 'Tested: 160 nodes, 0-hour retention',
    storageType: 'ssd',
    storageSizeGB: 4096, // 4 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 800, // Estimated for 32 vCPU, 64GB RAM, 4TB SSD
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-pb-cold',
    name: 'PB-Scale Cold Tier',
    description: 'Tested: 60 nodes, 24-hour lookback',
    storageType: 'ssd',
    storageSizeGB: 10240, // 10 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 1200, // Estimated for 32 vCPU, 64GB RAM, 10TB SSD
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-pb-frozen',
    name: 'PB-Scale Frozen Tier',
    description: 'Tested: 66 nodes, searchable snapshots',
    storageType: 'hdd', // Frozen tier typically uses cheaper storage
    storageSizeGB: 10240, // 10 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 500,
    throughputMBps: 300,
    costPerMonth: 1000, // Estimated for 32 vCPU, 64GB RAM, 10TB HDD
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-pb-master',
    name: 'PB-Scale Master Node',
    description: 'Tested: 3 nodes, no data storage',
    storageType: 'ssd',
    storageSizeGB: 100, // Minimal storage for OS/Elastic
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 600, // Estimated for 32 vCPU, 64GB RAM, minimal storage
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-pb-ml',
    name: 'PB-Scale ML Node',
    description: 'Tested: 1 node, machine learning',
    storageType: 'ssd',
    storageSizeGB: 100, // Minimal storage
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 600,
    deploymentTypes: ['gcp'],
  },
  {
    id: 'gcp-pb-kibana',
    name: 'PB-Scale Kibana/UI Node',
    description: 'Tested: 2 nodes, UI interface',
    storageType: 'ssd',
    storageSizeGB: 100, // Minimal storage
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 600,
    deploymentTypes: ['gcp'],
  },

  // Azure VM Sizes
  {
    id: 'azure-standard-d2s-v3',
    name: 'Standard_D2s_v3',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 50,
    cpuCores: 2,
    memoryGB: 8,
    iops: 3200,
    throughputMBps: 48,
    costPerMonth: 70,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-standard-d4s-v3',
    name: 'Standard_D4s_v3',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 4,
    memoryGB: 16,
    iops: 6400,
    throughputMBps: 96,
    costPerMonth: 140,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-standard-d8s-v3',
    name: 'Standard_D8s_v3',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 200,
    cpuCores: 8,
    memoryGB: 32,
    iops: 12800,
    throughputMBps: 192,
    costPerMonth: 280,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-standard-d16s-v3',
    name: 'Standard_D16s_v3',
    description: 'General purpose',
    storageType: 'ssd',
    storageSizeGB: 400,
    cpuCores: 16,
    memoryGB: 64,
    iops: 25600,
    throughputMBps: 384,
    costPerMonth: 560,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-standard-l8s',
    name: 'Standard_L8s',
    description: 'Storage optimized',
    storageType: 'nvme',
    storageSizeGB: 678,
    cpuCores: 8,
    memoryGB: 64,
    iops: 50000,
    throughputMBps: 500,
    costPerMonth: 500,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-standard-l16s',
    name: 'Standard_L16s',
    description: 'Storage optimized',
    storageType: 'nvme',
    storageSizeGB: 1356,
    cpuCores: 16,
    memoryGB: 128,
    iops: 100000,
    throughputMBps: 1000,
    costPerMonth: 1000,
    deploymentTypes: ['azure'],
  },

  // Azure Tested PB-Scale Configurations (based on real-world testing)
  {
    id: 'azure-pb-hot',
    name: 'PB-Scale Hot Tier',
    description: 'Tested: 160 nodes, 0-hour retention',
    storageType: 'ssd',
    storageSizeGB: 4096, // 4 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 850,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-pb-cold',
    name: 'PB-Scale Cold Tier',
    description: 'Tested: 60 nodes, 24-hour lookback',
    storageType: 'ssd',
    storageSizeGB: 10240, // 10 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 1250,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-pb-frozen',
    name: 'PB-Scale Frozen Tier',
    description: 'Tested: 66 nodes, searchable snapshots',
    storageType: 'hdd',
    storageSizeGB: 10240, // 10 TB
    cpuCores: 32,
    memoryGB: 64,
    iops: 500,
    throughputMBps: 300,
    costPerMonth: 1050,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-pb-master',
    name: 'PB-Scale Master Node',
    description: 'Tested: 3 nodes, no data storage',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 650,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-pb-ml',
    name: 'PB-Scale ML Node',
    description: 'Tested: 1 node, machine learning',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 650,
    deploymentTypes: ['azure'],
  },
  {
    id: 'azure-pb-kibana',
    name: 'PB-Scale Kibana/UI Node',
    description: 'Tested: 2 nodes, UI interface',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 32,
    memoryGB: 64,
    iops: 30000,
    throughputMBps: 3000,
    costPerMonth: 650,
    deploymentTypes: ['azure'],
  },

  // On-Premises Hardware Options
  {
    id: 'onprem-small',
    name: 'Small Server',
    description: 'Entry level',
    storageType: 'hdd',
    storageSizeGB: 1000,
    cpuCores: 4,
    memoryGB: 16,
    iops: 150,
    throughputMBps: 150,
    costPerMonth: 200,
    deploymentTypes: ['on_prem'],
  },
  {
    id: 'onprem-medium',
    name: 'Medium Server',
    description: 'Standard',
    storageType: 'ssd',
    storageSizeGB: 2000,
    cpuCores: 8,
    memoryGB: 32,
    iops: 10000,
    throughputMBps: 1000,
    costPerMonth: 500,
    deploymentTypes: ['on_prem'],
  },
  {
    id: 'onprem-large',
    name: 'Large Server',
    description: 'High performance',
    storageType: 'ssd',
    storageSizeGB: 5000,
    cpuCores: 16,
    memoryGB: 64,
    iops: 20000,
    throughputMBps: 2000,
    costPerMonth: 1200,
    deploymentTypes: ['on_prem'],
  },
  {
    id: 'onprem-premium',
    name: 'Premium Server',
    description: 'Enterprise',
    storageType: 'nvme',
    storageSizeGB: 2000,
    cpuCores: 32,
    memoryGB: 128,
    iops: 50000,
    throughputMBps: 3000,
    costPerMonth: 3000,
    deploymentTypes: ['on_prem'],
  },
  {
    id: 'onprem-storage',
    name: 'Storage Server',
    description: 'High capacity',
    storageType: 'hdd',
    storageSizeGB: 50000,
    cpuCores: 8,
    memoryGB: 32,
    iops: 500,
    throughputMBps: 300,
    costPerMonth: 800,
    deploymentTypes: ['on_prem'],
  },

  // Serverless (Elastic Serverless)
  {
    id: 'serverless-basic',
    name: 'Serverless Basic',
    description: 'Pay per use',
    storageType: 'ssd',
    storageSizeGB: 100,
    cpuCores: 2,
    memoryGB: 4,
    iops: 3000,
    throughputMBps: 250,
    costPerMonth: 0, // Pay per use
    deploymentTypes: ['serverless'],
  },
  {
    id: 'serverless-standard',
    name: 'Serverless Standard',
    description: 'Pay per use',
    storageType: 'ssd',
    storageSizeGB: 500,
    cpuCores: 4,
    memoryGB: 8,
    iops: 10000,
    throughputMBps: 1000,
    costPerMonth: 0, // Pay per use
    deploymentTypes: ['serverless'],
  },
  {
    id: 'serverless-premium',
    name: 'Serverless Premium',
    description: 'Pay per use',
    storageType: 'nvme',
    storageSizeGB: 1000,
    cpuCores: 8,
    memoryGB: 16,
    iops: 20000,
    throughputMBps: 2000,
    costPerMonth: 0, // Pay per use
    deploymentTypes: ['serverless'],
  },
];

export function getSKUsForDeployment(deploymentType: DeploymentType): HardwareSKU[] {
  return HARDWARE_SKUS.filter(sku => sku.deploymentTypes.includes(deploymentType));
}

export function getSKUById(id: string): HardwareSKU | undefined {
  return HARDWARE_SKUS.find(sku => sku.id === id);
}
